#ifndef TrekGFX_appvar_include_file
#define TrekGFX_appvar_include_file

#ifdef __cplusplus
extern "C" {
#endif

#define guiicons_palette_offset 0
#define deflected_width 16
#define deflected_height 16
#define TrekGFX_guiicons_deflected_index 0
#define deflected ((gfx_rletsprite_t*)TrekGFX_appvar[0])
#define icon_frequency_width 11
#define icon_frequency_height 11
#define TrekGFX_guiicons_icon_frequency_index 1
#define icon_frequency ((gfx_rletsprite_t*)TrekGFX_appvar[1])
#define icon_health_width 11
#define icon_health_height 11
#define TrekGFX_guiicons_icon_health_index 2
#define icon_health ((gfx_rletsprite_t*)TrekGFX_appvar[2])
#define icon_hullinteg_width 10
#define icon_hullinteg_height 10
#define TrekGFX_guiicons_icon_hullinteg_index 3
#define icon_hullinteg ((gfx_rletsprite_t*)TrekGFX_appvar[3])
#define icon_power_ok_width 10
#define icon_power_ok_height 10
#define TrekGFX_guiicons_icon_power_ok_index 4
#define icon_power_ok ((gfx_rletsprite_t*)TrekGFX_appvar[4])
#define icon_power_warn_width 10
#define icon_power_warn_height 10
#define TrekGFX_guiicons_icon_power_warn_index 5
#define icon_power_warn ((gfx_rletsprite_t*)TrekGFX_appvar[5])
#define icon_powerdraw_width 11
#define icon_powerdraw_height 11
#define TrekGFX_guiicons_icon_powerdraw_index 6
#define icon_powerdraw ((gfx_rletsprite_t*)TrekGFX_appvar[6])
#define icon_powerspend_width 11
#define icon_powerspend_height 11
#define TrekGFX_guiicons_icon_powerspend_index 7
#define icon_powerspend ((gfx_rletsprite_t*)TrekGFX_appvar[7])
#define icon_shieldinteg_width 10
#define icon_shieldinteg_height 10
#define TrekGFX_guiicons_icon_shieldinteg_index 8
#define icon_shieldinteg ((gfx_rletsprite_t*)TrekGFX_appvar[8])
#define icon_sourcemain_width 11
#define icon_sourcemain_height 11
#define TrekGFX_guiicons_icon_sourcemain_index 9
#define icon_sourcemain ((gfx_rletsprite_t*)TrekGFX_appvar[9])
#define icon_sourcereserve_width 11
#define icon_sourcereserve_height 11
#define TrekGFX_guiicons_icon_sourcereserve_index 10
#define icon_sourcereserve ((gfx_rletsprite_t*)TrekGFX_appvar[10])
#define mains_display_width 24
#define mains_display_height 24
#define TrekGFX_guiicons_mains_display_index 11
#define mains_display ((gfx_rletsprite_t*)TrekGFX_appvar[11])
#define shipinterior_left_width 160
#define shipinterior_left_height 240
#define TrekGFX_guiicons_shipinterior_left_index 12
#define shipinterior_left ((gfx_rletsprite_t*)TrekGFX_appvar[12])
#define shipinterior_right_width 160
#define shipinterior_right_height 240
#define TrekGFX_guiicons_shipinterior_right_index 13
#define shipinterior_right ((gfx_rletsprite_t*)TrekGFX_appvar[13])
#define tactical_display_width 24
#define tactical_display_height 24
#define TrekGFX_guiicons_tactical_display_index 14
#define tactical_display ((gfx_rletsprite_t*)TrekGFX_appvar[14])
#define particles_palette_offset 0
#define cracked_width 32
#define cracked_height 32
#define TrekGFX_particles_cracked_index 15
#define cracked ((gfx_rletsprite_t*)TrekGFX_appvar[15])
#define ship_palette_offset 0
#define side_width 24
#define side_height 24
#define TrekGFX_ship_side_index 16
#define side ((gfx_rletsprite_t*)TrekGFX_appvar[16])
#define top_width 24
#define top_height 24
#define TrekGFX_ship_top_index 17
#define top ((gfx_rletsprite_t*)TrekGFX_appvar[17])
#define moduleicons_palette_offset 0
#define lifesupport_width 12
#define lifesupport_height 12
#define TrekGFX_moduleicons_lifesupport_index 18
#define lifesupport ((gfx_rletsprite_t*)TrekGFX_appvar[18])
#define core_width 12
#define core_height 12
#define TrekGFX_moduleicons_core_index 19
#define core ((gfx_rletsprite_t*)TrekGFX_appvar[19])
#define thrusters_width 12
#define thrusters_height 12
#define TrekGFX_moduleicons_thrusters_index 20
#define thrusters ((gfx_rletsprite_t*)TrekGFX_appvar[20])
#define engines_width 12
#define engines_height 12
#define TrekGFX_moduleicons_engines_index 21
#define engines ((gfx_rletsprite_t*)TrekGFX_appvar[21])
#define warpdrive_width 12
#define warpdrive_height 12
#define TrekGFX_moduleicons_warpdrive_index 22
#define warpdrive ((gfx_rletsprite_t*)TrekGFX_appvar[22])
#define navsens_width 12
#define navsens_height 12
#define TrekGFX_moduleicons_navsens_index 23
#define navsens ((gfx_rletsprite_t*)TrekGFX_appvar[23])
#define transporter_width 12
#define transporter_height 12
#define TrekGFX_moduleicons_transporter_index 24
#define transporter ((gfx_rletsprite_t*)TrekGFX_appvar[24])
#define shields_width 12
#define shields_height 12
#define TrekGFX_moduleicons_shields_index 25
#define shields ((gfx_rletsprite_t*)TrekGFX_appvar[25])
#define armor_width 12
#define armor_height 12
#define TrekGFX_moduleicons_armor_index 26
#define armor ((gfx_rletsprite_t*)TrekGFX_appvar[26])
#define phasers_width 12
#define phasers_height 12
#define TrekGFX_moduleicons_phasers_index 27
#define phasers ((gfx_rletsprite_t*)TrekGFX_appvar[27])
#define torpedo_width 12
#define torpedo_height 12
#define TrekGFX_moduleicons_torpedo_index 28
#define torpedo ((gfx_rletsprite_t*)TrekGFX_appvar[28])
#define targsens_width 12
#define targsens_height 12
#define TrekGFX_moduleicons_targsens_index 29
#define targsens ((gfx_rletsprite_t*)TrekGFX_appvar[29])
#define TrekGFX_entries_num 30
extern unsigned char *TrekGFX_appvar[30];
unsigned char TrekGFX_init(void);

#ifdef __cplusplus
}
#endif

#endif
